# Generated by Django 4.2.7 on 2023-12-05 01:25

import account.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('cafe_name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('date_joined', models.DateTimeField(default=datetime.datetime.now, verbose_name='date joined')),
                ('last_login', models.DateTimeField(default=datetime.datetime.now, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=20)),
                ('qr_code', models.ImageField(blank=True, max_length=255, null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', account.models.MyAccountManager()),
            ],
        ),
    ]
