# Generated by Django 4.2.7 on 2023-12-03 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeMusics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_name', models.CharField(max_length=100)),
                ('artist_name', models.CharField(max_length=100)),
                ('music_image', models.URLField(max_length=500)),
                ('spotify_music_id', models.CharField(max_length=500, null=True)),
                ('music_duration', models.PositiveIntegerField(null=True)),
                ('cafe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpotifyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_access_token', models.CharField(max_length=500)),
                ('spotify_refresh_token', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=500, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MusicVotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_name', models.CharField(max_length=100, null=True)),
                ('customer_ip', models.GenericIPAddressField()),
                ('spotify_music_id', models.CharField(max_length=500, null=True)),
                ('vote_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.cafemusics')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentVotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_name', models.CharField(max_length=100, null=True)),
                ('customer_ip', models.GenericIPAddressField()),
                ('spotify_music_id', models.CharField(max_length=500, null=True)),
                ('vote_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.cafemusics')),
            ],
        ),
    ]
